### ISSUE TITLE
Excluded discovered changes cause the pull to fail

### ISSUE THREAD

**Issue by Gordonby** [Azure/AzOps#291]
**Describe the bug**
Where the SPN discovers two management groups roots, but the pipeline folder variable specified a subfolder path... then this causes the commit step to be empty.

**Steps to reproduce**

1. specify a pipeline folder like **"azops/dev (dev)"**
2. initiate a PULL using a pipeline that can discover other management group roots in addition to **dev**.
3. watch for the Commit step to fail, 

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	azops/dev2 (dev2)/

nothing added to commit but untracked files present (use "git add" to track)
##[error]Bash exited with code '1'.

**Screenshots**

**Comment by Gordonby** [comment]
Wanted to add that this bug is linked to #290 by virtue that a fix to either issue would solve the underlying problem I'm having -which without either fix is blocking me 🚫

**Comment by Gordonby** [comment]
I'm working around this by allowing empty commits explicitly.

```
- task: Bash@3
  displayName: "Commit changes to the repository"
  inputs:
    targetType: "inline"
    script: |
      git commit --allow-empty -m "$(commit_message)" -m "[skip ci]"
  condition: contains(variables['state'], 'continue')

```
